services:
  - type: web
    name: inventario-api
    env: php
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: cd inventarioBackend && php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_NAME
        value: Sistema de Gesti칩n de Inventario
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        sync: false  # Se configurar치 manualmente en Render con la URL de la BD
      - key: APP_KEY
        sync: false  # Se generar치 autom치ticamente en el build

